export const TEACHER_FORM_PATH = '/auth/register/teacher/form'

export const userType = {
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  PERSONAL: 'PERSONAL'
}

export const socialType = {
  FRIENDS_AND_FAMILY: 'FRIENDS_AND_FAMILY',
  COLLEAGUES_OR_CLIENTS: 'COLLEAGUES_OR_CLIENTS',
  STUDENTS: 'STUDENTS',
  OTHER: 'OTHER'
}

export const workplace = {
  SCHOOL: 'SCHOOL',
  HIGHER_EDUCATION:'HIGHER_EDUCATION',
  SCHOOL_ADMINSTRATION: 'SCHOOL_ADMINSTRATION',
  BUSINESS: 'BUSINESS'
}
